Feat add support descriptors match case
Spyrals-IO/ts-match pull request #14
Opened 2022-09-29 11:59 UTC by FabienCeppic

2022-09-29 14:02 UTC, Methrat0n requested changes

2022-09-29 14:02 UTC, Methrat0n commented on src/entries.ts
> +export const fromEntries = (entries: ReadonlyArray<[string, unknown]>): Record<string, unknown> =>
Remove it please, its not used anymore.

2022-09-30 13:12 UTC, FabienCeppic commented on src/does-match.ts
> +  if (entries(target as Record<string, unknown>).length === 0)
Ok

2022-09-30 13:12 UTC, FabienCeppic commented on src/does-match.ts
> +  const targetWithoutDescriptor: Array<[string, unknown]> = []
Ok

2022-09-30 13:13 UTC, FabienCeppic commented on src/does-match.ts
> +  entries(target as Record<string, unknown>).map((entry) => {
Ok

2022-10-03 12:51 UTC, merged